baseurl = "https://www.davidtorres.dev"
title = "David Torres - Software Engineer"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "David Torres"
    description = "Developer website"
    keywords = "blog,developer,personal"
    info = "Software Engineer"    
    gravatar = "torresdavid@gmail.com"    
    #avatarurl = "images/avatar2.jpg"

    #before you update update version with epoc time `date +%s` 
    footercontent = "1.1.0:1587495697"

    dateformat = "January 2, 2006"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "ABCDE"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/BizarroDavid"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/theantifeed"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/datorres/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/bizarrodavid/"
    

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "https://strangeday.press/"

            [[languages.en.menu.main]]
            name = "Resume"
            weight = 2
            url = "pdfs/resume-david-torres.pdf"

            [[languages.en.menu.main]]
            name = "Publications"
            weight = 4
            url = "publications/publications/index.html"

            [[languages.en.menu.main]]
            name = "Email"
            weight = 5
            url = "mailto:torresdavid@gmail.com"


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "production"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"
# This bucket is blocked from the public.
URL = "s3://anti-prod-personal-landing-page?region=us-west-1"


# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

    